import type { Metadata } from "next";
import "./globals.css";
import { ConfigProvider } from "antd";

// const Vazir = localFont({
//   src: [
//     {
//       path: "./fonts/Vazir.woff2", // ✅ correct relative path
//       weight: "400",
//       style: "normal",
//     },
//   ],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body dir="rtl">
        <ConfigProvider
          theme={{
            token: {
              fontFamily: "Vazir",
            },
          }}
        >
          {children}
        </ConfigProvider>
      </body>
    </html>
  );
}
